version: "2"

services:
  kafka-0:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=ODg3OGVhNDcwNjJjNDNjMm
  kafka-1:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=ODg3OGVhNDcwNjJjNDNjMm
  kafka-2:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=ODg3OGVhNDcwNjJjNDNjMm
